spring:
  profiles: 
  application:
    name: microservicecloud-zuul-gateway
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-zuul-gateway
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-zuul-gateway