server:
  port: 8081
spring:
  profiles: dev
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eurek
---
server:
  port: 8082
spring:
  profiles: test
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/